(function(g){var window=this;var a1=function(a){var b={languageCode:a.l,languageName:a.o,displayName:g.oz(a),kind:a.u,name:a.A,id:a.Ea,is_servable:a.G,is_default:a.isDefault,is_translateable:a.D,vss_id:a.B};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},b1=function(a){return a.g?a.g.languageCode:a.l},Nna=function(a,b){var c=new g.nz;
c.l=a.l;c.o=a.o;c.A=a.A;c.u=a.u;c.isDefault=!1;c.D=a.D;c.B=a.B;c.F=a.F;c.g=b;return c},c1=function(a){if(!Ona.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Pna,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Qna=function(){this.l=[];
this.g=[]},d1=function(a,b){return b?a.g.concat(a.l):a.g},e1=function(a,b){switch(b.u){case "asr":var c=a.l;
g.bb(c,(0,g.y)(b.Qq,b))||c.push(b);break;default:c=a.g,g.bb(c,(0,g.y)(b.Qq,b))||c.push(b)}},f1=function(){g.F.call(this);
this.l=new Qna;this.A=[]},g1=function(a,b,c){f1.call(this,a);
this.g=null;this.A=b.Nu;this.o=c},h1=function(){this.Wa=[]},i1=function(a,b,c,d,e,f){g.F.call(this);
this.O=a;this.u=b;this.B=new h1;this.g=null;this.G=d;this.L=f;this.l=this.o=null;this.F=c;this.D=e||!1;this.I=new g.L(this.Uw,1E3,this);g.H(this,this.I);this.A=new g.Vr(this);g.H(this,this.A);g.R(g.W(b).experiments,"html5_disable_captions_seek_complete")?this.A.K(b,"seekto",this.Vx):this.A.K(b,"seekcomplete",this.UG);this.Vx(b.getCurrentTime());this.Uw()},j1=function(a,b){b-=a.u.Cc();
var c=a.g;a.g=g.Za(a.F.Oe(b).g);c!=a.g&&a.L&&a.L()},k1=function(a,b){var c=g.Bv(b,a.O,{}).Mb(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.l=g.jr(c,d,3,100).then((0,g.y)(a.vL,a));a.o=b;c=a.B;d=a.o.g[0].l;var e=g.wb(c.Wa,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Wa[e-1]&&e<c.Wa.length&&1==c.Wa[e]-d?(g.jb(c.Wa,e),g.jb(c.Wa,e-1)):0<e&&1==d-c.Wa[e-1]?c.Wa[e-1]=d:e<c.Wa.length&&1==c.Wa[e]-d?c.Wa[e]=d:(g.sb(c.Wa,e,0,d),g.sb(c.Wa,e+1,0,d)))},l1=function(a,b){f1.call(this,g.W(b));
this.g=a;this.D=b;this.o=null;this.u=!1;this.B=g.Yy(g.W(this.D))&&!this.g.l},m1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.$T(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.nz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Rna=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},n1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.$T(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},o1=function(a,b,c,d,e){f1.call(this,e||null);
c=c||g.Bq(a).hl||"";c=c.split("_").join("-");this.u=g.Dq(a,{hl:c});this.o=b;this.B=!!d;this.D={};this.g=null},p1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.yD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.o=f;this.l=k},q1=function(a,b,c,d,e){g.yD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},s1=function(a){a=void 0===a?{}:a;
var b="_"+r1++;return new q1(0,0x8000000000000,0,b,a)},u1=function(a,b,c,d,e,f,k){var l={};
g.Wa(l,b);g.Wa(l,a.params);g.Wa(l,c);var m={};g.Wa(m,b.ub);a.params.ub&&g.Wa(m,a.params.ub);g.Wa(m,c.ub);l.ub=m;g.U.call(this,{C:"div",H:"caption-window",M:{id:"caption-window-"+a.id,dir:1==l.Ig?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},J:[{C:"span",H:"captions-text"}]});this.u=[];this.Z=!1;this.o=a;this.F=[];this.L=[];this.Xa=e;this.Ta=f;this.Sa=k;this.B=this.I=null;this.ga=.96*e;this.xa=.96*f;this.l=l;this.Ja=c;this.A=this.g["captions-text"];this.Da=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.X=d/360*16;this.type=0;this.ma=this.X*t1(m);a=new g.as(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.TG,this);a.subscribe("dragmove",this.SG,this);a.subscribe("dragend",this.QG,this);this.ua=this.oa=0;b="";this.l.windowOpacity&&(a=c1(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Sna[this.l.textAlign]};this.Da&&(a["border-radius"]=
b?this.ma/8+"px":"");if(this.D=!g.R(this.Sa,"web_player_vertical_and_ruby_captions_killswitch")&&(2==this.o.params.Ig||3==this.o.params.Ig))b=this.element,c="vertical-rl",1==this.l.NA&&(c="vertical-lr"),g.ne&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.$h(b,"-o-writing-mode",c),g.$h(b,"-webkit-writing-mode",c),g.$h(b,"writing-mode",c),g.$h(b,"text-orientation","upright"),3==this.o.params.Ig&&(g.$h(b,"text-orientation",""),g.$h(b,"transform","rotate(180deg)"));g.$h(this.element,a);switch(this.l.cg){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},t1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},v1=function(a,b){var c={},d=b.background?b.background:a.l.ub.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.ub.backgroundOpacity;d=c1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Da&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ma/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.X*t1(b)+"px";d=1;e=b.color||a.l.ub.color;if(b.color||null!=b.textOpacity)e=c1(e),d=null==b.textOpacity?a.l.ub.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Vu&&(k=e=b.Vu);var l=a.X/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=u;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Vq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.ub.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ve&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.jm&&(c.visibility="hidden");return c},w1=function(a,b,c){a.Z=a.Z||!!c;
var d={};g.Wa(d,a.l.ub);g.Wa(d,c||b.l);g.Wa(d,a.Ja.ub);c=a.F[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.jm==!!c.jm&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.F.length;e++)if(g.Ac(d,a.F[e])){var f=a.L[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ve("SPAN");g.$h(f,v1(a,e));a.L[0].appendChild(f);e=1}a.L.length=e;a.F.length=e}else a.L.length=0,a.F.length=0,f=g.ve("SPAN"),g.$h(f,v1(a,d)),a.A.appendChild(f);k=!d.jm;e=(c=g.t(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.u.length||!b.o){if(0<l||0!=a.u.length){var n=g.ve("BR");f.appendChild(n)}k&&a.kp(f)}m&&(k?a.I:f).appendChild(c?g.we(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.$h(k[c],v1(a,d)),g.$h(k[c],"font-size","50%");a.F.push(d);a.L.push(f);a.u.push(b)},x1=function(){},z1=function(){this.u=this.l=this.mode=this.o=0;
this.A=new y1(this);this.B=new y1(this);this.g=[];this.clear()},Tna=function(a,b,c){if(255==a&&255==b||!a&&!b)return{wl:a,
xl:b,result:0};a=A1[a];b=A1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{wl:a,xl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{wl:a,xl:b,result:2};return{wl:a,xl:b,result:3}},Una=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.u&&a.reset(),a.A.g.clear(),a.B.g.clear()):(a.u=0,B1(a.A,b,c,d))},Vna=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?Una(a,d.Pu,d.Qu,b):1==d.type&&a.o&496&&B1(a.B,d.Pu,d.Qu,b)}a.g.length=0},C1=function(){this.g=0},D1=function(){this.l=this.o=this.g=0},E1=function(){this.timestamp=this.Vd=0},F1=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new E1}this.g=this.l=this.row=0;this.style=new C1;this.A=a;this.u=0},G1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.A.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var u=a.o[m][p];
if(0!=u.Vd){0==c&&(c=m,d=p);n=String.fromCharCode(u.Vd);var x=u.timestamp;x<e&&(e=x);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.Vd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.A.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.o[k][m],u=p.Vd,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),x=p.timestamp,x<=e&&(e=x),l+=n,p.reset()),32==m||0==u)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},$na=function(a,b){switch(a){case 0:return Wna[(b&127)-32];
case 1:return Xna[b&15];case 2:return Yna[b&31];case 3:return Zna[b&31]}return 0},H1=function(a){return a.o[a.row][a.l]},I1=function(a,b,c){2<=b&&1<a.l&&(--a.l,H1(a).Vd=0);
var d=H1(a);d.timestamp=a.A.l+0;d.Vd=$na(b,c);32>a.l&&a.l++},J1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].kg(a.o[c+e][f])},K1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},L1=function(a){a.row=0<a.g?a.g:1;
a.l=1;K1(a,0,15)},M1=function(a){this.u=a;
this.A=0;this.style=new C1;this.B=new F1(a);this.D=new F1(a);this.F=new F1(a);this.l=this.B;this.o=this.D;this.g=this.l},N1=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:G1(d,c),L1(a.l),L1(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.u.mode=1<<d.u;e?d.l=1:d.g!=b&&(d.g>b?(G1(d,c),K1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},O1=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.u.mode=1<<a.g.u},P1=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.u.mode=1<<a.g.u},y1=function(a){this.l=a;
this.g=new D1;this.A=0;this.o=new M1(a);this.B=new M1(a);this.u=this.o},B1=function(a,b,c,d){a.g.update();
b=Tna(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.wl;c=b.xl;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.u.g,b&96&&I1(a,0,b),c&96&&I1(a,0,c),0!=b&&0!=c&&3==a.style.g&&G1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.B:a.o,a.u=b,a.l.mode=1<<(a.A<<2)+(b.A<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.A<<2)+(b.A<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;J1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));K1(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:I1(b.g,0,32);break a;case 48:57==c?(b=b.g,H1(b).Vd=0,32>b.l&&b.l++):I1(b.g,1,c&15)}break;case 2:c&32&&I1(b.g,2,c&31);break;case 3:c&32&&I1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:O1(b);break;case 33:b=
b.g;1<b.l&&(--b.l,H1(b).Vd=0);break;case 36:b=b.g;d=H1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:N1(b,2,d);break;case 38:N1(b,3,d);break;case 39:N1(b,4,d);break;case 40:I1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.u.mode=1<<b.g.u;break;case 42:d=b.F;d.g=15;d.style.set(4);L1(d);P1(b);break;case 43:P1(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:G1(a,d)}K1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;G1(a,d);J1(a,b,b+1,a.g-1);K1(a,a.row,1)}break;case 46:K1(b.o,0,15);break;case 47:G1(b.l,d);d=b.o;a=b.u.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;O1(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},Q1=function(a){g.F.apply(this,arguments)},R1=function(a,b){Q1.call(this);
this.O=b;this.u={};this.G={};this.I={};this.A="_"+r1++;this.B=a;this.F={};this.l=this.g=null;this.D=!0},S1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},T1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},U1=function(a,b){var c=S1(a,b);
return void 0!=c?c:null},W1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return V1.test(c),c},X1=function(a,b){var c={},d=b.getAttribute("ws");
g.Wa(c,d?a.I[d]:a.B);d=U1(b,"mh");null!=d&&(c.Lq=d);d=U1(b,"ju");null!=d&&(c.textAlign=d);d=U1(b,"pd");null!=d&&(c.Ig=d);d=U1(b,"sd");null!=d&&(c.NA=d);d=W1(b,"wfc");null!=d&&(c.windowColor=d);d=S1(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},Y1=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Wa(c,a.G[d]);d=U1(b,"ap");null!=d&&(c.cg=d);d=S1(b,"cc");null!=d&&(c.av=d);d=S1(b,"ah");null!=d&&(c.Xe=d);d=S1(b,"rc");null!=d&&(c.xs=d);d=S1(b,"av");null!=d&&(c.Kg=d);return c},Z1=function(a,b,c,d){var e={};
g.Wa(e,Y1(a,b));g.Wa(e,X1(a,b));d?g.Ac(e,a.B)?(d=a.A,e=a.B):d="_"+r1++:d=b.getAttribute("id")||"_"+r1++;a=S1(b,"t")+c;b=S1(b,"d")||0x8000000000000;return new q1(a,b,0,d,e)},$1=function(a,b,c,d,e,f,k){u1.call(this,a,b,c,d,e,f,k);
this.type=1},a2=function(a,b,c){this.D=c;
this.version=this.B=this.u=this.g=0;this.l=new DataView(a);this.o=[]},b2=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},c2=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},d2=function(a,b){Q1.call(this);
this.l=a;this.track="CC3"==b.o?4:0;this.g=new z1;this.g.o=1<<this.track},f2=function(a){if(g.t(a))return!1;
a=new a2(a,8,0);return e2(a)},e2=function(a){if(!(a.g<a.l.byteLength)||1380139777!=c2(a))return!1;
a.version=b2(a);if(1<a.version)return!1;b2(a);b2(a);b2(a);return!0},g2=function(a,b,c,d,e,f,k){u1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.T=this.P=this.ca=0;this.R=NaN;this.ya=0;this.Ga=null;this.ka=new g.L(this.AL,433,this);g.H(this,this.ka)},aoa=function(a,b){return(a.D?b.offsetHeight:b.offsetWidth)+1},boa=function(a){if(isNaN(a.R)){var b=a.l.av;
if(b){var c=g.ve("SPAN");g.Ge(c,"\u2013".repeat(b));g.$h(c,v1(a,a.l.ub));a.A.appendChild(c);a.R=c.offsetWidth;a.A.removeChild(c)}else a.R=0}return a.R},coa=function(a,b){if(!b)return"";
a.D&&1!=a.o.params.NA&&(b*=-1);return"translate"+(a.D?"X":"Y")+"("+b+"px)"},h2=function(a){a.G=Array.prototype.slice.call(g.ge("ytp-rollup-caption-line-wrapper"));
for(var b=a.o.params.xs,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.D?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.P=d;a.T=Math.max(boa(a),a.ya,aoa(a,a.A))},doa=function(a,b){h2(a);
var c=a.G.reduce(function(b,c){return(a.D?c.offsetWidth:c.offsetHeight)+b},0);
c=a.P-c;if(c!=a.ca){var d=0<c&&0==a.ca;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.xo(a.ka));g.$h(a.A,"transform",coa(a,c));a.ca=c}h2(a)},i2=function(){Q1.call(this)},j2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ve=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new p1(b,c,d,e.id,p.nodeValue,f||0<n,g.wc(l)?void 0:l);m.push(p);var u=e;g.H(u,p);u.l.push(p)}else u={},g.Wa(u,l),j2(a,b,c,d,e,!0,p,u,m)}},k2=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},l2=function(a,b,c,d){d=Object.assign({Lq:0},d);
return new q1(a,b,c,"_"+r1++,d)},m2=function(a){g.F.call(this);
this.l=a;this.g=null},p2=function(a){g.eK.call(this,a);
this.o=g.W(a);this.u=a.getVideoData();this.xa=g.CJ(a);this.O=a;var b=null,c=g.jp("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Uo(c));this.Z=b;this.A={ub:{}};this.B={ub:{}};this.I=[];this.P={};this.aa={};this.L=!1;this.oa=g.aU(this.u,this.O);this.ya=!!this.u.captionTracks.length;this.Ga=!!this.u.jj;this.ma="3"==this.o.u;b=a.app.u;c=!(!b||!b.Wk());this.ua=!(!b||!b.Dh());this.D=this.ma&&c&&!this.oa;this.R=!this.D&&this.ma&&this.ua&&this.oa;this.l=this.F=this.G=this.T=this.ka=null;this.X=
new m2(this.o);g.H(this,this.X);this.Da=g.R(this.o.experiments,"web_player_subtitles_reset_trusted_method_killswitch");c=b=this.g=null;this.D||(b=new g.uo(this.eB,void 0,this),g.H(this,b),c=new g.L(this.WM,2E3,this),g.H(this,c));this.ha=b;this.ca=c;this.ba=new g.Vr(this);g.H(this,this.ba);this.D||this.ba.K(a,"resize",this.ct);this.ba.K(a,"onPlaybackAudioChange",this.ZI);this.ba.K(a,g.BD("captions"),this.ZE,this);this.ba.K(a,"crx_captions",this.aF,this);n2(this,o2(this,"display-settings")||{})},q2=
function(a){if(1==a.o.gg||1==a.u.gg||"alwayson"==g.rB(a.u,"yt:cc"))return!0;
if(2==a.o.gg){var b=o2(a,"module-enabled");if(null!=b)return!!b}if(a.u.captionTracks.length)var c=a.player.getAudioTrack().Wo;return"ON"==c||"on"==g.rB(a.u,"yt:cc")},r2=function(a,b){if(a.g&&(void 0===b||!b)||!a.u.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Ql||"FORCED_ON"==c.Wo},t2=function(a,b){if(a.l){if(a.F&&a.F.g)return a.F.g;
var c=b;c||(c=a.Ga?a.u.Ch||a.o.Ch:a.ya?!1:!0);c=d1(a.l.l,c);for(var d=[a.u.fg,a.o.fg,g.rB(a.u,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(b1(c[f])==d[e])return c[f];return a.F&&a.F.mp?a.F.mp:(d=c.find(function(a){return a.isDefault}))?d:c[0]||s2(a)}return null},s2=function(a){return a.F&&a.F.Ql},u2=function(a){var b=s2(a);
return!!b&&a.g==b},v2=function(a,b){for(var c=a.O.app.u.ia().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},x2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.L=c,a.L&&w2(a,"module-enabled",!!b));a.g=b;r2(a)&&(a.g=s2(a));a.load()},eoa=function(a,b){var c=g.LL(a.xa,!0).height;
if(!c)return null;var d=a.xa.Fa();switch(null!=b.params.Lq?b.params.Lq:1<b.l.length?1:0){case 1:return new $1(b,a.A,a.B,c,d.width,d.height,a.o.experiments);case 2:return new g2(b,a.A,a.B,c,d.width,d.height,a.o.experiments);default:return new u1(b,a.A,a.B,c,d.width,d.height,a.o.experiments)}},n2=function(a,b,c){var d=y2.ub;
a.A={};g.Wa(a.A,y2);a.A.ub={};g.Wa(a.A.ub,d);a.B={ub:{}};var e=b.backgroundOverride?a.B:a.A,f=b.background||d.background;V1.test(f);e.ub.background=f;e=b.colorOverride?a.B:a.A;f=b.color||d.color;V1.test(f);e.ub.color=f;e=b.windowColorOverride?a.B:a.A;f=b.windowColor||y2.windowColor;V1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.B:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ub.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.B:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.ub.fontSizeIncrement=f;f=b.fontStyleOverride?a.B:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Ve?3:d.bold?1:d.Ve?2:0);f=f.ub;switch(e){case 1:f.bold=!0;delete f.Ve;break;case 2:delete f.bold;f.Ve=!0;break;case 3:f.bold=!0;f.Ve=!0;break;default:delete f.bold,delete f.Ve}e=b.textOpacityOverride?a.B:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ub.textOpacity=f;e=b.windowOpacityOverride?a.B:a.A;f=b.windowOpacity;null==f&&(f=y2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.B:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.ub.charEdgeStyle=f;e=b.fontFamilyOverride?a.B:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ub.fontFamily=f;a.loaded&&a.ct();c&&w2(a,"display-settings",b)},A2=function(a,b){if(b&&!a.G){var c=s1({Ig:0,
lang:"en"});a.G=[c,new p1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.LJ(a.player,a.G)}else!b&&a.G&&(z2(a,a.G),a.G=null)},z2=function(a,b){g.OJ(a.player,b);
(0,g.A)(b,function(a){g.kb(this.I,a)},a);
a.ha.Hj()},B2=function(a,b){return a&&g.t(a)&&V1.test(a)?a:b},C2=function(a,b){return g.Ga(a)&&!isNaN(a)?Math.max(0,Math.min(1,parseFloat(a))):b},foa=function(a,b){return g.Ga(a)&&!isNaN(a)?g.Sd(a,-2,4):b},o2=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},w2=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.KD.prototype.lj=g.ca(13,function(){for(var a=g.fe(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Ae(a[b])});
g.SV.prototype.lj=g.ca(12,function(){this.l.lj()});
g.KD.prototype.Wk=g.ca(11,function(){return!!this.g.textTracks});
g.SV.prototype.Wk=g.ca(10,function(){return this.l.Wk()});
g.KD.prototype.dj=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.SV.prototype.dj=g.ca(8,function(a){this.l.dj(a)});
g.zC.prototype.Dh=g.ca(7,function(){});
g.KD.prototype.Dh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.SV.prototype.Dh=g.ca(5,function(){return this.l.Dh()});
g.nz.prototype.Qq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.qt.prototype.Zl=g.ca(2,function(a){return(a=this.pg(a))?a.l:0});
g.kw.prototype.Zl=g.ca(1,function(){return 0});
var goa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Pna=/#(.)(.)(.)/,Ona=/^#(?:[0-9a-f]{3}){1,2}$/i,V1=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(f1,g.F);f1.prototype.Oz=function(){return!1};
f1.prototype.U=function(){this.Lg();g.F.prototype.U.call(this)};
g.r(g1,f1);g1.prototype.Hq=function(a,b,c){b=this.Ej(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.Lg();this.g=g.Mq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
g1.prototype.Iq=function(a){if(this.o)for(var b=g.q(this.o.captionTracks),c=b.next();!c.done;c=b.next())e1(this.l,c.value);a()};
g1.prototype.Ej=function(a,b){var c=a.Mb(),d={fmt:b};a.g&&(d.tlang=b1(a));return g.Dq(c,d)};
g1.prototype.Lg=function(){this.g&&this.g.abort()};
h1.prototype.contains=function(a){a=g.wb(this.Wa,a);return 0<=a||0>a&&1==(-a-1)%2};
h1.prototype.length=function(){return this.Wa.length/2};
g.r(i1,g.F);g.h=i1.prototype;g.h.U=function(){g.F.prototype.U.call(this);this.l&&this.l.cancel()};
g.h.Vx=function(a){var b=this;if(this.F.di())var c=this.A.K(this.u,"progresssync",function(){b.F.index.Ub()&&(b.reset(),b.g=null,j1(b,b.u.getCurrentTime()),b.A.Pa(c))});
else j1(this,a)};
g.h.UG=function(){j1(this,this.u.getCurrentTime())};
g.h.reset=function(){this.B=new h1;this.l&&(this.l.cancel(),this.l=null)};
g.h.Uw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Of(a);!a||this.l||this.g&&30<this.g.startTime-this.u.getCurrentTime()||(a=this.g,a=a.g.mi(a),a.g[0].duration&&(this.B.contains(a.g[0].l)||k1(this,a),this.g=g.Za(a.g)));this.I.start()};
g.h.vL=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status,c=g.rw(a);c?(a=g.Bv(this.o,this.O,{}),b=this.o,g.wv(b.l,a,c),b.requestId=a.get("req_id"),k1(this,this.o)):(b||null===this.G||(this.D?this.G(a.response,1E3*(this.o.g[0].startTime+this.u.Cc())):this.G(a.responseText,1E3*(this.o.g[0].startTime+this.u.Cc()))),this.l=this.o=null)};
g.r(l1,f1);g.h=l1.prototype;g.h.Hq=function(a,b,c){this.Lg();b=Rna(this,a.getId());b||(b=a.l,b=this.g.l?n1(this,b,"386"):n1(this,b));if(b){var d=1E3*(b.index.Zl(b.index.xe())-b.index.qd(b.index.xe()));this.o=new i1(new g.Ru,this.D,b,function(b,f){c(b,a,f,d)},this.B||g.Ku(b.info),(0,g.y)(function(){this.o&&this.o.reset();
this.u=!0},this))}};
g.h.Oz=function(){var a=this.u;this.u=!1;return a};
g.h.Iq=function(a){var b;this.B?b=[new g.nz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.nz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.l?m1(this,"386"):m1(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())e1(this.l,c.value);a()};
g.h.Lg=function(){this.o&&(this.o.dispose(),this.o=null)};
g.h.Ej=function(){return""};
g.r(o1,f1);o1.prototype.Hq=function(a,b,c){b=this.Ej(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.Lg();this.g=g.Mq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
o1.prototype.Iq=function(a){var b=this.u,c={type:"list",tlangs:1,v:this.o,vssids:1};this.B&&(c.asrs=1);b=g.Dq(b,c);c=(0,g.y)(function(b){this.g=null;if((b=b.responseXML)&&b.firstChild){for(var c=g.q(b.getElementsByTagName("track")),d=c.next();!d.done;d=c.next()){var k=d.value;d=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),u="true"==k.getAttribute("lang_default"),x="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
e1(this.l,new g.nz({languageCode:d,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:x,vss_id:k,is_default:u}))}b=b.getElementsByTagName("target");c=b.length;for(d=0;d<c;d++)l=b[d].getAttribute("lang_code"),m=b[d].getAttribute("lang_translated"),n=b[d].getAttribute("lang_original"),p=b[d].getAttribute("id"),u="true"==b[d].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,is_default:u},this.D[l.languageCode]=l.languageName,this.A.push(new g.mz(l))}a()},
this);
this.Lg();this.g=g.Mq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
o1.prototype.Ej=function(a,b){var c=this.u,d={v:this.o,type:"track",lang:a.l,name:a.A,kind:a.u,fmt:b};a.g&&(d.tlang=b1(a));return c=g.Dq(c,d)};
o1.prototype.Lg=function(){this.g&&this.g.abort()};var Sna=["left","right","center","justify"];var y2={windowColor:"#080808",windowOpacity:0,textAlign:2,cg:7,Xe:50,Kg:100,ub:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(p1,g.yD);p1.prototype.toString=function(){return g.yD.prototype.toString.call(this)};g.r(q1,g.yD);q1.prototype.toString=function(){return g.yD.prototype.toString.call(this)};
var r1=0;g.r(u1,g.U);g.h=u1.prototype;g.h.TG=function(a,b){var c=g.pi(this.element,this.element.parentElement);this.oa=a-c.x;this.ua=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.SG=function(a,b){var c=g.si(this.element),d=a-this.oa-.02*this.Xa,e=b-this.ua-.02*this.Ta,f=(d+c.width/2)/this.ga*3;f=Math.floor(g.Sd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.Sd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ga;d=100*g.Sd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.Sd(c,0,1);this.o.params.cg=l;this.o.params.Kg=c;this.o.params.Xe=d;this.l.cg=l;this.l.Kg=c;this.l.Xe=d;this.jA()};
g.h.QG=function(){g.oo(this.element,"ytp-dragging")};
g.h.jA=function(){this.zh(this.u)};
g.h.zh=function(a){var b=Math.min(this.Yv(),this.ga),c=this.Xv(),d="";3==this.o.params.Ig&&(d="rotate(180deg)");g.$h(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Ko(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Xe+2;d=this.l.cg;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Kg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.$h(this.element,a)};
g.h.Ko=function(a){var b;for(b=0;b<a.length&&a[b]==this.u[b];b++);if(this.Z||this.u.length>b)b=0,this.Z=!1,this.u=[],this.F=[],this.L=[],this.I=this.B=null,g.ye(this.A);for(;b<a.length;b++)w1(this,a[b])};
g.h.Yv=function(){return 0};
g.h.Xv=function(){return 0};
g.h.kp=function(a){this.B=g.ve("SPAN");this.B.appendChild(g.we("\u00a0"));this.I=g.ve("SPAN");g.J(this.I,"caption-visual-line");this.B.appendChild(this.I);this.B.appendChild(g.we("\u00a0"));a.appendChild(this.B)};
g.h.toString=function(){return g.U.prototype.toString.call(this)};x1.prototype.A=function(){};z1.prototype.clear=function(){this.u=this.l=this.mode=0;this.g=[];this.reset()};
z1.prototype.reset=function(){this.mode=0;this.A.reset(0);this.B.reset(1)};
var A1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];C1.prototype.set=function(a){this.g=a};
C1.prototype.get=function(){return this.g};
D1.prototype.clear=function(){this.g=0};
D1.prototype.update=function(){this.g=2==this.g?1:0};
D1.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
E1.prototype.kg=function(a){this.Vd=a.Vd;this.timestamp=a.timestamp};
E1.prototype.reset=function(){this.timestamp=this.Vd=0};
F1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.Vd?a+"_":a+String.fromCharCode(d.Vd)}a+="\n"}return a};
F1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.u=a;this.g=0;this.l=this.row=1};
var Wna=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Xna=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Yna=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Zna=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];M1.prototype.reset=function(a,b){this.A=b;this.style.set(2);this.l=this.B;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.B.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
y1.prototype.reset=function(a){this.A=a;this.g.clear();this.u=this.o;this.o.reset(a,0);this.B.reset(a,1)};g.r(Q1,g.F);Q1.prototype.reset=function(){};g.r(R1,Q1);R1.prototype.reset=function(){this.F={};this.l=this.g=null;this.D=!0};
R1.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.u,l={},m=c.getAttribute("p");m&&g.Wa(l,this.u[m]);m=T1(c,"b");null!=m&&(l.bold=
m);m=T1(c,"i");null!=m&&(l.Ve=m);m=T1(c,"u");null!=m&&(l.underline=m);m=U1(c,"et");null!=m&&(l.charEdgeStyle=m);m=U1(c,"of");null!=m&&(l.offset=m);m=W1(c,"bc");null!=m&&(l.background=m);m=W1(c,"ec");null!=m&&(l.Vu=m);m=W1(c,"fc");null!=m&&(l.color=m);m=U1(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=S1(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=S1(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=S1(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=U1(c,"rb");null!=c&&(l.aN=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.I[d]=X1(this,c);break;case "wp":d=c.getAttribute("id"),this.G[d]=Y1(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=Z1(this,d,e,!1);g.H(this,this.g);(d=this.F[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.F[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.A;m=!!T1(d,"a");n=(S1(d,"t")||0)+n;var p=S1(d,"d")||5E3;m||(!this.D&&
this.l&&this.l.windowId==l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=""));var u=m?6:5,x=this.u[d.getAttribute("p")],B=d.childNodes;B.length&&(this.D=null!=d.getAttribute("d"));for(var D=0;D<B.length;D++){var G=B[D];0<D&&(m=!0);var O=void 0;1==G.nodeType&&(O=G);if(O&&"s"==O.tagName)if((G=this.u[O.getAttribute("p")])&&1==G.aN&&!g.R(this.O.experiments,"web_player_vertical_and_ruby_captions_killswitch")){G=n;var Q=p,Va=l,Gb=m,Db=u;var Nc=O;var cg=B[D+1],Ih=B[D+2],Ec=B[D+3];
Nc.getAttribute("p");S1(Nc,"t");S1(cg,"t");S1(Ih,"t");S1(Ec,"t");O=g.ve("RUBY");Nc=Nc.textContent;var Mk=g.ve("SPAN");Mk.innerText=Nc;O.appendChild(Mk);cg.getAttribute("p");Mk=g.ve("RP");Nc=cg.textContent;Mk.innerText=Nc;O.appendChild(Mk);Ih.getAttribute("p");Nc=Ih.textContent;cg=g.ve("RT");cg.innerText=Nc;O.appendChild(cg);Ec.getAttribute("p");Nc=Ec.textContent;Ec=g.ve("RP");Ec.innerText=Nc;O.appendChild(Ec);G=new p1(G,Q,Db,Va,O,Gb,null);D+=3}else Ec=O,G=n,Q=p,Va=l,Gb=m,Db=u,O=Ec.textContent?Ec.textContent:
"",Nc=this.u[Ec.getAttribute("p")],Ec=S1(Ec,"t")||0,G=new p1(G+Ec,Q-Ec,Db,Va,O,Gb,Nc);else G=new p1(n,p,u,l,G.textContent||"",m,x);k.push(G);this.l=G}if(0<k.length)for(k[0].windowId==this.A&&(this.g=Z1(this,d,e,!0),g.H(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.H(l,k),l.l.push(k),c.push(k)}e=c}else e=[];return e};g.r($1,u1);$1.prototype.Ko=function(a){var b=this.o.l;u1.prototype.Ko.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Wa(d,c.l);g.Wa(d,hoa);var e=c.l;var f=d}w1(this,c,d)}};
var hoa={jm:!0};g.r(a2,x1);a2.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+r1++;c=c/1E3-this.D;d=d/1E3-this.D;a=new q1(c,d-c,5,f,{textAlign:0,cg:0,Xe:2.5*b,Kg:5.33*a});e=new p1(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.r(d2,Q1);d2.prototype.o=function(a){a=new a2(a,a.byteLength,this.l);if(e2(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.u=c2(a)*(1E3/45):1==a.version&&(a.u=4294967296*c2(a)+c2(a)),a.B=b2(a);0<a.B;a.B--){var b=b2(a),c=b2(a),d=b2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.u,type:this.track,Pu:c,Qu:d,order:b.g.length}))}Vna(this.g,a);return a.o}return[]};
d2.prototype.reset=function(){this.g.clear()};g.r(g2,u1);g.h=g2.prototype;g.h.jA=function(){g.yo(this.ka)};
g.h.AL=function(){g.oo(this.element,"ytp-rollup-mode");this.zh(this.Ga,!0)};
g.h.Xv=function(){return this.D?this.T:this.P};
g.h.Yv=function(){return this.D?this.P:this.T};
g.h.kp=function(a){u1.prototype.kp.call(this,a);g.J(this.B,"ytp-rollup-caption-line-wrapper");g.$h(this.B,"display","inline-block");g.$h(this.I,"display","inline-block")};
g.h.zh=function(a,b){this.Ga=a;if(this.o.params.xs){for(var c=0,d=0;d<this.u.length&&c<a.length;d++)this.u[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.u.concat(a.slice(c)));this.ya=this.T;this.P=this.T=0;u1.prototype.zh.call(this,a);doa(this,b);u1.prototype.zh.call(this,a)}else u1.prototype.zh.call(this,a)};g.r(i2,Q1);
i2.prototype.o=function(a,b){for(var c=[],d=a.split(ioa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!joa.test(f)){var l=D2.exec(f);if(l&&4<=l.length){var m=k2(l[1]),n=k2(l[2])-m;m+=k;var p,u=p=void 0,x=void 0,B=void 0,D=l[3];l={textAlign:2};D=g.q(D?D.split(" "):[]);for(var G=D.next();!G.done;G=D.next())if(G=G.value.split(":"),2==G.length){var O=G[1];switch(G[0]){case "line":G=O.split(",");G[0].endsWith("%")&&(B=G[0],l.Kg=Number.parseInt(B,10),2==G.length&&(x=G[1].trim()));break;case "position":G=O.split(",");
u=G[0];l.Xe=Number.parseInt(u,10);2==G.length&&(p=G[1].trim());break;case "align":switch(O){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}B||(l.Kg=100,x||(x="end"));if(!u)switch(l.textAlign){case 0:l.Xe=0;break;case 1:l.Xe=100;break;default:l.Xe=50}u=0;switch(x){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(p){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.cg=0>u||8<u?7:u;p=l;f=f.substring(D2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=l2(m,n,5,u),n=new p1(m,n,5,k.id,p,!1,g.wc(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.l.push(n);else for(x=p.split(koa),1==x.length?(p=5,u=l2(m,n,p,u)):(B=p=6,u=Object.assign({av:32},u),u=new q1(m,n,B,"_"+r1++,u)),c.push(u),B=m,l=0;l<x.length;l++)D=x[l],0==l%2?(G=g.qo("<html>"+D+"</html>"),G.getElementsByTagName("parsererror").length?
(O=G.createElement("span"),O.appendChild(G.createTextNode(D))):O=G.firstChild,j2(this,B,n-(B-m),p,u,0<l,O,f,c)):B=k2(D)+k}D2.lastIndex=0}}return c};
var joa=/^NOTE/,ioa=/(?:\r\n|\r|\n){2,}/,D2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),koa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(m2,g.F);m2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
m2.prototype.reset=function(){this.g&&this.g.reset()};
m2.prototype.U=function(){this.clear();g.F.prototype.U.call(this)};g.r(p2,g.eK);g.h=p2.prototype;g.h.U=function(){if(this.D||this.R){var a=this.O.app.u;a&&a.lj()}else A2(this,!1);g.eK.prototype.U.call(this)};
g.h.Qk=function(){return this.ma?this.D||this.R:r2(this)?!0:q2(this)};
g.h.load=function(){g.eK.prototype.load.call(this);this.F=this.player.getAudioTrack();if(this.l)this.g&&(this.X.clear(),this.D?v2(this,!0):3!=this.player.Aa()&&this.l.Hq(this.g,"srv3",(0,g.y)(this.dM,this))),this.g&&!u2(this)?this.player.na("captionschanged",a1(this.g)):this.player.na("onCaptionsTrackListChanged");else{var a;this.oa?a=new l1(this.u.la,this.player):this.ya?a=new g1(this.o,this.u,this.player.getAudioTrack()):a=new o1(this.u.jj,this.u.videoId,this.u.fg||this.o.fg||g.rB(this.u,"yt:cc_default_lang")||
this.o.Qb,this.u.Uo,this.o);this.l=a;g.H(this,this.l);a.Iq((0,g.y)(this.cM,this))}};
g.h.unload=function(){this.D&&this.g?v2(this,!1):(this.ca&&g.zo(this.ca),g.PJ(this.player,"captions"),this.I=[],this.l&&this.l.Lg(),this.X.clear(),this.G&&g.LJ(this.player,this.G),this.ct());g.eK.prototype.unload.call(this);var a=g.X(this.player.app);a&&a.u&&g.nC(a.u.o);this.player.na("captionschanged",{})};
g.h.cM=function(){var a;this.L||q2(this)?a=t2(this,this.L):r2(this)&&(a=s2(this));if(this.D||this.R){for(var b=d1(this.l.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.oz(e),srclang:b1(e),id:e.toString()};this.R||(f.src=this.l.Ej(e,"vtt"));e==a&&(f["default"]=1);c.push(g.te("TRACK",f))}this.O.app.u.dj(c);a=this.O.app.u.ia();this.ua&&this.ba.K(a.textTracks,"change",this.eM)}else!this.g&&a&&x2(this,a),this.player.na("onCaptionsTrackListChanged"),this.player.na("onApiChange")};
g.h.eM=function(){for(var a=this.O.app.u.ia().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=d1(this.l.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&x2(this,b,!0)};
g.h.zN=function(){!this.g&&this.D||this.unload()};
g.h.dM=function(a,b,c,d){if(a){this.l.Oz()&&(this.I=[],g.PJ(this.O,"captions"),this.ha.Hj(),this.X.reset());var e=this.X;c=c||0;d=d||0;if(!g.t(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Nt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!f2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],u=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|u&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.t(a)){if("WEBVTT"==a.substring(0,6)){b=a;var x=c;e.g||(e.g=new i2);var B=e.g.o(b,x);.01>Math.random()&&g.Up(Error("Deprecated subtitles format in web player: WebVTT"));var D=B}else b:{B=a;x=g.qo(B);if(!x||!x.firstChild)throw Error("Invalid caption track data: "+
B);if("timedtext"==x.firstChild.tagName){if(3==parseInt(x.firstChild.getAttribute("format"),10)){if(!e.g){B={};var G=b1(b);G&&(B.lang=G,goa.test(G)&&(B.Ig=1));e.g=new R1(B,e.l)}D=e.g.o(x,c);break b}throw Error("Unsupported subtitles format in web player (Format2): "+B);}if("transcript"==x.firstChild.tagName)throw Error("Unsupported subtitles format in web player (Format1): "+B);throw Error("Invalid caption track data: "+B);}var O=D}else{D=a;x=c;G=d;if(!f2(D))throw Error("Invalid binary caption track data");
e.g||(e.g=new d2(G,b));O=e.g.o(D,x)}var Q=O}catch(Va){g.M(Va),e.clear(),Q=[]}else Q=[];g.LJ(this.player,Q);!this.L||this.R||u2(this)||g.Oy(this.o)||g.Py(this.o)||(g.zo(this.ca),Q=s1({cg:0,Xe:5,Kg:5,xs:2,textAlign:0,Ig:0,lang:"en"}),this.T=[Q],e=["Click "," for settings"],this.ka||(O=new g.PB(g.aP()),g.H(this,O),this.ka=O.element),O=Q.end-Q.start,(b=g.oz(this.g))&&this.T.push(new p1(Q.start,O,0,Q.id,b)),this.T.push(new p1(Q.start,O,0,Q.id,e[0]),new p1(Q.start,O,0,Q.id,this.ka,!0),new p1(Q.start,O,
0,Q.id,e[1],!0)),g.LJ(this.player,this.T),g.xo(this.ca));!this.L||this.R||u2(this)||(w2(this,"module-enabled",!0),this.F&&(this.F.g=this.g),(Q=g.X(this.player.app))&&Q.u&&g.nC(Q.u.o));this.L=!1}};
g.h.ZE=function(a){this.I.push(a);this.ha.Hj()};
g.h.aF=function(a){g.kb(this.I,a);this.l instanceof l1&&this.l.B&&g.OJ(this.player,[a]);this.ha.Hj()};
g.h.QM=function(a){if(a instanceof q1){var b=this.P[a.id];b&&b.o!=a&&(b.dispose(),delete this.P[a.id],b=null);b||(b=eoa(this,a))&&(this.P[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.WM=function(){z2(this,this.T);this.T=null};
g.h.eB=function(){this.ha.stop();g.xc(this.aa);this.I.sort(g.AD);var a=this.I;if(this.G){var b=(0,g.Ce)(a,function(a){return-1==this.G.indexOf(a)},this);
b.length&&(a=b)}(0,g.A)(a,this.QM,this);g.jc(this.P,function(a,b){this.aa[b]?(a.element.parentNode||g.TJ(this.player,a.element,4),a.zh(this.aa[b])):(a.dispose(),delete this.P[b])},this)};
g.h.iA=function(){n2(this,{},!0)};
g.h.Fp=function(){var a=y2.ub;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ve?3:a.bold?1:a.Ve?2:0,textOpacity:a.textOpacity,windowColor:y2.windowColor,windowOpacity:y2.windowOpacity};var b=o2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.it=function(a,b){var c={};g.Wa(c,o2(this,"display-settings"));g.Wa(c,a);n2(this,c,b);this.player.N("captionssettingschanged")};
g.h.ct=function(){!this.D&&this.loaded&&(g.jc(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.eB())};
g.h.gc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Sd(b,-2,4);this.it({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&x2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.o.tb&&w2(this,"module-enabled",!!b);break;case "track":if(!this.l)return{};if(b){if(this.D)break;if(!g.Oa(b))break;if(g.wc(b)){x2(this,null,!0);break}for(var d=d1(this.l.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.o!=b.languageName||(c=b.translationLanguage?Nna(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||x2(this,c,!0)}else return this.loaded&&this.g&&!u2(this)?a1(this.g):{};return"";case "tracklist":return this.l?(0,g.E)(d1(this.l.l,!(!b||!b.includeAsr)),function(a){return a1(a)}):[];
case "translationLanguages":return this.l?this.l.A:[];case "displaySettings":c=this.Fp();if(g.Oy(this.o)&&b&&g.Oa(b))if(b.reset&&this.Da)this.iA();else{d={};null!=b.color&&(d.color=B2(b.color,c.color),d.colorOverride=!0);null!=b.background&&(d.background=B2(b.background,c.background),d.backgroundOverride=!0);null!=b.windowColor&&(d.windowColor=B2(b.windowColor,c.windowColor),d.windowColorOverride=!0);null!=b.textOpacity&&(d.textOpacity=C2(b.textOpacity,c.textOpacity),d.textOpacityOverride=!0);null!=
b.backgroundOpacity&&(d.backgroundOpacity=C2(b.backgroundOpacity,c.backgroundOpacity),d.backgroundOpacityOverride=!0);null!=b.windowOpacity&&(d.windowOpacity=C2(b.windowOpacity,c.windowOpacity),d.windowOpacityOverride=!0);null!=b.charEdgeStyle&&(e=g.FY[b.charEdgeStyle],d.charEdgeStyle=g.Ga(e)?e:c.charEdgeStyle,d.charEdgeStyleOverride=!0);null!=b.fontSizeIncrement&&(d.fontSizeIncrement=foa(b.fontSizeIncrement,c.fontSizeIncrement),d.fontSizeIncrementOverride=!0);e=b.fontFamilyOption;if(null!=b.fontFamily||
null!=e)e=g.EY[null!=b.fontFamily?b.fontFamily:e],d.fontFamily=g.Ga(e)?e:c.fontFamily,d.fontFamilyOverride=!0;null!=b.fontStyle&&(e=g.GY[b.fontStyle],d.fontStyle=g.Ga(e)?e:c.fontStyle,d.fontStyleOverride=!0);this.it(d,!0);c=this.Fp()}d=c;d.fontFamilyOption=g.Sla[c.fontFamily];d.charEdgeStyle=g.Tla[c.charEdgeStyle];d.fontStyle=g.Ula[c.fontStyle];return d;case "sampleSubtitles":this.D||void 0==b||A2(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.o.tb&&a.push("stickyLoading");return a};
g.h.Fj=function(){var a=this.g;return a?{cc:a.B}:{}};
g.h.VA=function(){this.loaded&&this.g&&!u2(this)?(w2(this,"module-enabled",!1),this.unload(),r2(this,!0)&&x2(this,s2(this),!1)):x2(this,u2(this)||!this.g?t2(this,!0):this.g,!0)};
g.h.ZI=function(){var a=u2(this);r2(this,a)?x2(this,this.player.getAudioTrack().Ql,!1):this.u.captionTracks.length&&(this.loaded&&this.unload(),this.Qk()&&(a?x2(this,t2(this),!1):this.load()))};g.gU.captions=p2;})(_yt_player);
